Document: lunar-land
Title: Debian lunar-land Manual
Author: <insert document author here>
Abstract: This manual describes what lunar-land is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/lunar-land/lunar-land.sgml.gz

Format: postscript
Files: /usr/share/doc/lunar-land/lunar-land.ps.gz

Format: text
Files: /usr/share/doc/lunar-land/lunar-land.text.gz

Format: HTML
Index: /usr/share/doc/lunar-land/html/index.html
Files: /usr/share/doc/lunar-land/html/*.html
